[tools]
"cargo:stylua" = "latest"
"cargo:tree-sitter-cli" = "latest"
"github:LuaLS/lua-language-server" = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:github.com/hashicorp/terraform-ls" = "latest"
"go:github.com/segmentio/golines" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:eslint" = "latest"
"npm:eslint_d" = "latest"
"npm:graphql-language-service-cli" = "latest"
"npm:opencode-ai" = "latest"
"npm:pyright" = "latest"
"npm:typescript-language-server" = "latest"
"pipx:black" = "latest"
"pipx:httpie" = "latest"
"pipx:pre-commit" = "latest"
"pipx:trash-cli" = "latest"
awscli = "latest"
bat = "latest"
btop = { version = "latest", os = ["linux"] }
elixir = "latest"
erlang = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
gitleaks = "latest"
go = "latest"
jq = "latest"
node = "latest"
oh-my-posh = "latest"
pipx = "latest"
python = "latest"
redis = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
